### ISSUE TITLE
Need config/frontmatter syntax

### ISSUE THREAD

**Issue by srawlins** [dart-lang/expected_output#13]
I opened an issue for config and comment syntax (#12), but then went off the rails and focused 100% on comments.

So, as for a config syntax, in order to meet what [dart_style uses](https://github.com/dart-lang/dart_style/blob/master/test/formatter_test.dart#L166..L171) today, we should just provide a front matter parse, similar to [Jekyll front matter](https://jekyllrb.com/docs/frontmatter/), but with less ceremony.

**How about: text that precedes the first >>> is front matter:**

```
40 columns                              |
>>> split all chained calls if they don't fit on one line
input
>>>
output
```

Each [DataCase](https://github.com/dart-lang/expected_output/blob/master/lib/expected_output.dart#L170) yielded by expected_output for this data file can include a member, `frontMatter`, which is just the raw text found before the first `>>>` (`40 columns                              |`). This should work fine with dart_style's usage, although may slow down testing in that the test needs to parse `40 columns                              |` once per test case, rather than per file (not a big slow down).

**Comment by srawlins** [comment]
WDYT @munificent @pq

**Comment by pq** [comment]
I'm slightly inclined to suggest something explicit like Jekyll's triple-dashes to make it super obvious that this is front matter and not a mistake but don't feel strongly either way.

PS: Neat!

**Comment by srawlins** [comment]
If we do something more structured like that, we can maybe satisfy the nice readability of

```
40 columns                              |
```

and yield key/value pairs as config, and allow comments?

```
---
// 40 columns                           |
pageWidth: 40
---
>>> test case 1
input
<<<
expected output
```

which can add to a `config` member on each DataCase? `{'pageWidth': '40'}`.

**Comment by munificent** [comment]
I personally lean towards making the front matter implicit as any text before the first `>>>`. I'd like to minimize the amount of non-content text in these files to make them easier to read, write, and maintain if possible.

I haven't wanted any config properties yet, so allowing comments and key-values isn't useful to me. Maybe make that opt-in?
